Upgrade to Laravel 6

diff --git a/larahex b/larahex
--- a/larahex
+++ b/larahex
@@ -37,13 +37,10 @@ echo "Project Name: $PROJECTNAME"
 # Create empty laravel app
 composer global update || err "Failed to global-update composer"
 composer global require "laravel/installer" || err "Failed to install laravel/installer package"
-composer create-project laravel/laravel $PROJECTNAME || err "Failed to create laravel/laravel project"
+composer create-project laravel/laravel $PROJECTNAME "6.*" || err "Failed to create laravel/laravel project"
 
 echo "Entering project directory $PROJECTNAME" && cd $PROJECTNAME
 [[ $(pwd) =~ ${PROJECTNAME} ]] || err "Failed to enter into the ./$PROJECTNAME/ directory"
-
-# Make artisan executable
-chmod +x ./artisan || warn "Failed to set +x on ./artisan"
 
 # Install Twig
 composer require rcrowe/twigbridge || err "Failed to install rcrowe/twigbridge package"
@@ -62,7 +59,8 @@ php artisan preset none || err "Failed to set artisan preset none"
 php artisan preset bootstrap || err "Failed to set artisan preset bootstrap"
 
 # Add authentication
-php artisan make:auth || err "Failed to apply Laravel authentication scaffolding"
+composer require laravel/ui
+php artisan make:auth || php artisan ui bootstrap --auth || err "Failed to apply Laravel authentication scaffolding"
 
 # Blade > Twig
 wget https://raw.githubusercontent.com/uvarovserge/blade2twig/master/blade2twig.php || err "Could not download blade2twig.php"
@@ -97,5 +95,3 @@ npm install
 echo ""
 echo "Your application is ready!"
 echo ""
-
-# TODO: should we do artisan publish everything?
